In [ ]:
                #   Assignment name:- Exploratory Data Analysis (EDA Basics)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\HP\\Downloads\\House Price India.csv")

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.fillna(df.median(numeric_only=True), inplace=True)

In [7]:
# Q1. Average, Median, and Standard Deviation of House Prices

avg_price = df['Price'].mean()
median_price = df['Price'].median()
std_price = df['Price'].std()

print("Average Price:", avg_price)
print("Median Price:", median_price)
print("Standard Deviation:", std_price)

Average Price: 538932.2183310534
Median Price: 450000.0
Standard Deviation: 367532.38080396695

In [9]:
# Q2. Most Common Number of Bedrooms

df['number of bedrooms'].mode()

0    3
Name: number of bedrooms, dtype: int64

In [10]:
# Q3. Check Whether Price Data is Skewed

df['Price'].skew()

np.float64(4.269297720707117)

In [11]:
# Q4. Average Price for Each Bedroom Count

df.groupby('number of bedrooms')['Price'].mean()

number of bedrooms
1     3.089638e+05
2     3.985476e+05
3     4.632776e+05
4     6.361988e+05
5     7.752550e+05
6     8.375815e+05
7     1.016544e+06
8     1.208455e+06
9     7.766663e+05
10    8.200000e+05
11    5.200000e+05
33    6.400000e+05
Name: Price, dtype: float64

In [12]:
# Q5. Relationship Between Area and Price

# (Area without basement)

df[['Area of the house(excluding basement)', 'Price']].corr()

,Area of the house(excluding basement),Price
Area of the house(excluding basement),1.00000,0.61522
Price,0.61522,1.00000

In [13]:
# Q6. High Price but Low Area Houses

df[(df['Price'] > df['Price'].quantile(0.90)) &
   (df['Area of the house(excluding basement)'] <
    df['Area of the house(excluding basement)'].quantile(0.25))]

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
1125,6762811652,42510,4,3.25,2790,5420,1.0,0,3,3,...,1963,2013,122050,52.9998,-114.576,2530,7200,2,55,970000
1210,6762811058,42511,3,1.75,1610,7200,1.0,0,0,3,...,1973,0,122047,52.8579,-114.477,3790,7200,2,67,1180000
1517,6762811059,42517,3,2.50,1970,23180,1.0,1,4,3,...,1937,1998,122016,52.7795,-114.588,3030,34689,2,60,1180000
2154,6762811108,42526,3,1.50,2170,16600,1.0,1,2,3,...,1979,0,122005,52.8607,-114.278,3130,13875,2,53,1150000
8517,6762811560,42621,3,1.75,1810,24586,1.0,0,4,4,...,1983,0,122057,52.7614,-114.412,3540,14200,2,55,990000
10262,6762811494,42650,3,2.25,2300,15952,1.0,0,0,4,...,1963,0,122071,52.8622,-114.422,2200,14284,3,79,1000000
10507,6762811048,42655,2,1.75,2080,8112,1.0,1,4,4,...,1939,1984,122022,52.9434,-114.467,2030,8408,3,65,1190000
10922,6762812074,42662,4,2.00,1190,8190,1.5,0,0,3,...,1945,0,122007,52.9208,-114.587,1190,1567,1,80,900000
13163,6762812046,42704,2,1.50,1140,7800,1.0,0,0,4,...,1947,0,122048,52.8442,-114.399,2020,7800,3,60,903000
13713,6762811776,42713,3,1.75,2150,4200,1.0,0,4,5,...,1960,0,122009,52.7971,-114.595,2510,7500,3,68,950000
14024,6762811879,42719,2,1.50,1800,4500,1.0,0,2,3,...,1942,0,122061,52.8605,-114.537,2270,3840,3,72,930000

In [14]:
# Q7. Average Price Based on Floors and Waterfront

df.groupby(['number of floors', 'waterfront present'])['Price'].mean()

number of floors  waterfront present
1.0               0                     4.323724e+05
                  1                     1.211081e+06
1.5               0                     5.476162e+05
                  1                     1.232507e+06
2.0               0                     6.357742e+05
                  1                     2.075931e+06
2.5               0                     1.087654e+06
                  1                     3.280000e+06
3.0               0                     5.558095e+05
                  1                     1.655000e+06
3.5               0                     1.205875e+06
Name: Price, dtype: float64

In [15]:
# Q8. Minimum and Maximum House Price

print("Minimum Price:", df['Price'].min())

print("Maximum Price:", df['Price'].max())

Minimum Price: 78000
Maximum Price: 7700000

In [16]:
# Q9. Postal Code with Highest Average Price

df.groupby('Postal Code')['Price'].mean().sort_values(ascending=False).head(1)

Postal Code
122071    2.348311e+06
Name: Price, dtype: float64

In [ ]:
# Q10. Write at least 5 insights from your analysis

# Insight 1
# House prices are positively skewed because a few luxury houses increase the average price.

# Insight 2
# Most houses have a common bedroom count such as 3 or 4 bedrooms.

# Insight 3
# Larger living areas usually increase house prices.

# Insight 4
# Waterfront houses are generally more expensive.

# Insight 5
# Some postal codes have much higher average prices, indicating premium locations.